# Generated by Django 3.2.8 on 2021-12-01 22:52

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageA',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageB',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageC',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageD',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageE',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='imageF',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[320, 240], upload_to='images/'),
        ),
    ]
