# Generated by Django 3.2.8 on 2021-12-02 00:51

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('baseApp', '0006_auto_20211201_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='imageA',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageB',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageC',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageD',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imageF',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1280, 720], upload_to='images/'),
        ),
    ]
